[package]
name = "elf2uf2-rs"
version = "1.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2018"

description = "Port of elf2uf2 to rust"
documentation = "https://docs.rs/elf2uf2-rs"
readme = "README.md"
license = "0BSD"
repository = "https://github.com/JoNil/elf2uf2-rs"

[dependencies]
assert_into = "1.1"
clap = "3.0.0-beta.2"
once_cell = "1.5"
static_assertions = "1"
zerocopy = "0.3"