[package]
name = "elf2uf2-rs"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_into = "1.1"
clap = "3.0.0-beta.2"
static_assertions = "1"
zerocopy = { git = "https://github.com/JoNil/zerocopy.git" }